name: Register source_id
description: Register a new model for the CORDEX CV.
title: "[source_id]: "
labels: ["register source-id"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time!
  - type: input
    id: source-id
    attributes:
      label: source-id
      description: A short identifier of the model.
      placeholder: ex. `REMO2020` or `WRF442Q`
    validations:
      required: false
  - type: dropdown
    id: license
    attributes:
      label: What license do you choose?
      multiple: false
      options:
        - CC0
        - CC BY 4.0
