name: Process source-id
on:
  repository_dispatch:
    types: [register-command]
concurrency: 'main'
jobs:
  process_source_id:
    #if: github.event.label.name == 'register source-id'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: run python
        id: infos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          table=`python labels.py /repos/{owner}/{repo}/issues/${{ github.event.client_payload.github.payload.issue.number }}`
          echo $table
          echo "table=$table" >> $GITHUB_OUTPUT

      - name: Show info passed
        run: |
          echo ${{ steps.infos.outputs.table }}

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/${{ steps.infos.outputs.table }}.yaml
          issue-body: ${{ github.event.client_payload.github.payload.issue.body }}

      - name: update table
        id: update
        run: |
          id_added=`python update-${{ steps.infos.outputs.table }}.py '${{ steps.issue-parser.outputs.jsonString }}'`
          echo "id_added=$id_added" >> $GITHUB_OUTPUT

      
   #  - name: Commit changes
   #     shell: bash
   #     run: |
   #       git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
   #       git config --global user.name "github-actions[bot]" && \
   #       git add source_id.json && \
   #       git commit -m 'added source_id' && \
   #       git push
   #   - name: Create Pull Request
   #     uses: peter-evans/create-pull-request@v5
   #     with:
   #       title: add ${{ steps.issue-parser.outputs.issueparser_${{ steps.infos.outputs.table }} }}
   #       commit-message: add-${{ steps.issue-parser.outputs.issueparser${{ steps.infos.outputs.table }} }}
   #       branch: add-${{ steps.issue-parser.outputs.issueparser${{ steps.infos.outputs.table }} }}
   #       body: |
   #         Closes #${{ github.event.client_payload.github.payload.issue.number }}
   #         Request to add ${{ steps.issue-parser.outputs.issueparser${{ steps.infos.outputs.table }} }}
   #       delete-branch: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: add ${{ steps.update.outputs.id_added }}
          commit-message: add-${{ steps.update.outputs.id_added }}
          branch: add-${{ steps.update.outputs.id_added }}
          body: |
            Closes #${{ github.event.client_payload.github.payload.issue.number }}
            Request to add ${{ steps.issue-parser.outputs.issueparser${{ steps.infos.outputs.table }} }}
          delete-branch: true
