name: Process source-id
on:
  issues:
    types: opened
concurrency: 'main'
jobs:
  process_source_id:
    #if: github.event.label.name == 'register source-id'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/source_id.yaml

   #   - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > source_id.json
      
      - run: python update-source_id.py '${{ steps.issue-parser.outputs.jsonString }}'
      
   #  - name: Commit changes
   #     shell: bash
   #     run: |
   #       git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
   #       git config --global user.name "github-actions[bot]" && \
   #       git add source_id.json && \
   #       git commit -m 'added source_id' && \
   #       git push
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: add ${{ steps.issue-parser.outputs.source_id }}
          commit-message: add-${{ steps.issue-parser.outputs.source_id }}
          branch: add-${{ steps.issue-parser.outputs.source_id }}
          delete-branch: true
