name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'register source-id'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get content
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
      - name: Add comment
        uses: peter-evans/create-or-update-comment@5f728c3dae25f329afbe34ee4d08eef25569d79f
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:
            
  run-python-test:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
  
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
  
    - name: Execute Test Script
      run: python parse-issue-body.py "${{ github.event.issue.body }}"
